# Generated by Django 4.1.7 on 2023-03-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=25)),
                ('modelcolor', models.CharField(max_length=10)),
                ('modelsize', models.FloatField()),
                ('modelprice', models.IntegerField()),
                ('modelqnty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SliperModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=25)),
                ('modelcolor', models.CharField(max_length=10)),
                ('modelsize', models.FloatField()),
                ('modelprice', models.IntegerField()),
                ('modelqnty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SportsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=25)),
                ('modelcolor', models.CharField(max_length=10)),
                ('modelsize', models.FloatField()),
                ('modelprice', models.IntegerField()),
                ('modelqnty', models.IntegerField()),
            ],
        ),
    ]
